language: julia

julia:
  - 1.5
  
os:
  - linux
  - osx
  - windows

before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get update; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get upgrade -y; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install build-essential -y; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install -y cmake mesa-utils; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install -y libxrandr-dev libxinerama-dev libxcursor-dev mesa-utils; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install -y ffmpeg; fi
  - if [ $TRAVIS_OS_NAME = linux ]; ENV["DISPLAY"] = ":0"; fi

notifications:
  email:
    - nwgreen@umich.edu

jobs:
  include:
    - stage: "Documentation"
      julia: 1.5
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip


